### ISSUE TITLE
Database some tables question

### ISSUE THREAD

**Issue by Iglesias-Leafwind** [davidgmorais/IESproject#13]
2 of our tables on our db have only 1 primary key like moviebytype and starredin
so basically we can only have 1 genre associated with 1 movie but not more than 1 movie
and the same for actors and movies

**Comment by 0ceanCat** [comment]
ah yes, you are right, i will fix the problem, one min.

**Comment by Iglesias-Leafwind** [comment]
hmmm 3 minutes ago u said one minute 🤔

**Comment by 0ceanCat** [comment]
keep calm

**Comment by 0ceanCat** [comment]
done

**Comment by Iglesias-Leafwind** [comment]
💯
