### ISSUE TITLE
Add cinema

### ISSUE THREAD

**Issue by marianabladeiro** [davidgmorais/IESproject#18]
We still need to decide how to handle the authenticity of someone who wants to add their cinema.

**Comment by marianabladeiro** [comment]
We also need to decide how we will ask for the information about rooms and seats

**Comment by 0ceanCat** [comment]
sure, and i think that we need send an email with info of payment to user

**Comment by Iglesias-Leafwind** [comment]
We don't actually need to fully implement a payment method we only need to simulate one.
Client and Cinema will have a flag that will determine if they are a cinema or a client.
