### ISSUE TITLE
Login and register

### ISSUE THREAD

**Issue by marianabladeiro** [davidgmorais/IESproject#19]
How to handle login and register both on the website and api

**Comment by 0ceanCat** [comment]
for normal users its easy, a simple register form is enough, but for cinema... idk, how can we verify that user has a  cinema?

**Comment by Iglesias-Leafwind** [comment]
On the webpage user can be a client or a cinema or an admin.
client is as easy as going to email
while cinema needs to show proof (via email or in person with a document) (here we can simply had a button which chooses between creating cinema user or client user)
We also need to have 4 admin accounts each for one of us who will run the server and there will be no way of creating more admin accounts.
