### ISSUE TITLE
Update reports

### ISSUE THREAD

**Issue by Iglesias-Leafwind** [davidgmorais/IESproject#7]
Update reports for next iteration.

**Comment by marianabladeiro** [comment]
Should we aggregate tickets for the same session and movie in the same object or should we separate them into single tickets?

**Comment by Iglesias-Leafwind** [comment]
Yeah I think it is better.

**Comment by marianabladeiro** [comment]
How do we handle each cinema room layout?

**Comment by 0ceanCat** [comment]
i created new tables: room, seat. Also did some changes in data base script. i think that now we are able to handle each cinema room layout.
