### ISSUE TITLE
Create core endpoints.

### ISSUE THREAD

**Issue by Iglesias-Leafwind** [davidgmorais/IESproject#9]
Create the following core endpoints for the api.
login
register
change password
delete account
add movie
remove movie
edit movie
search movie (default most recent release)
search movie by actor
search movie by director
search movie by title
search movie by genre
search movie by year (we will keep all movies from 5 years ago to the most recent release)
search movie by popularity (basically by rating)
check movie info
add favourite movie to the current user
remove favourite movie to the current user
check notifications (this is for the mobile app)

**Comment by Iglesias-Leafwind** [comment]
Missing endpoints:
delete account
add movie       (only admin permission)
remove movie (only admin permission)
edit movie       (only admin permission)

**Comment by 0ceanCat** [comment]
only admin permission? i think cinemas should have permission to do the same thing

**Comment by Iglesias-Leafwind** [comment]
Yes but cinemas shouldn't be able to add/edit/remove movies they can sell tickets from pre-existing movies.
Our DB will be filled with movies from the script or an admin (in our case us) running the website
